# Generated by Django 2.1.7 on 2019-02-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefMovie', '0002_movies_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
