# Generated by Django 2.1.7 on 2019-02-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefMovie', '0003_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image/movie/'),
        ),
    ]
